booky/urls.py
from django.contrib import admin
from django.urls import path,include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contact.urls')),

]

contact/urls.py
from django.urls import path
from .  import views



urlpatterns = [

    path('', views.index, name='index'),
    path('add-contact/', views.addContact, name='add-contact'),
    path('edit-contact/<str:pk>', views.editContact, name='edit-contact'),
    path('delete/<str:pk>', views.deleteContact, name='delete'),
    path('profile/<str:pk>', views.contactProfile, name='profile'),
    path('konekte/',views.konekte,name='konekte'),
    path('dekonekte/',views.dekonekte,name='dekonekte'),
    path('newuser/',views.newuser,name='newuser'),
    path('',views.akey,name='akey'),
    
    

   

]

contact/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
import random


# Create your models here.

class Contact(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='contact')
    full_name = models.CharField(max_length=250,null=True,blank=True)
    relationship = models.CharField(max_length=250,null=True,blank=True)
    email = models.EmailField(max_length=254,null=True,blank=True)
    phone_number = models.CharField(max_length=20,default='')
    address = models.CharField(max_length=1000,default='inconnu',null=True,blank=True)

    def __str__(self):
          return self.full_name



class NewUser(models.Model):
    non = models.CharField(max_length = 255)
    modpas = models.CharField(max_length=255)
    modpas2 = models.CharField(max_length=255)

    
    def __str__(self):
        return self.non

    class Meta:
        verbose_name = 'Itilizate'
        verbose_name_plural = 'Itilizate yo'

contact/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import *
from django.contrib.auth.models import User

class NewUserForm(forms.ModelForm):
    modpas = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'my-input-class'}),
        label='Modpas'
    )
    modpas2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'my-input-class'}),
        label='Tape modpas ou ankò pou konfime li'
    )

    class Meta:
        model = NewUser
        fields = ("non", "modpas", "modpas2")  

    def clean(self):
        cleaned_data = super().clean()
        non = cleaned_data.get('non')  
        modpas = cleaned_data.get('modpas')
        modpas2 = cleaned_data.get('modpas2')

        if len(modpas) < 8:
            self.add_error('modpas', 'Modpas la dwe gen 8 karakte minimòm')

        if modpas2 != modpas:
            self.add_error('modpas2', 'Modpas yo pa koresponn!')

contact/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
from .models import Contact
from .forms import NewUserForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required


def akey(request):
    konekte = request.user.is_authenticated
    context = {
        'konekte': konekte
    }
    return render(request, 'base.html', context)

def konekte(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            non = request.POST.get("non")
            modpas = request.POST.get("modpas")
            user = authenticate(username=non, password=modpas)

            if user is not None:
                login(request, user)
                print('identifikasyon an fet')
                return redirect(akey)
            else:
                print('idantifyan yo pa korek...')

        context = {}
        return render(request, 'konekte.html', context)
    else:
        return redirect(akey)
@login_required
def dekonekte(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect(akey)
    else:
        return redirect(akey)
    
    
def newuser(request):
    if request.method == 'POST':
        form = NewUserForm(data=request.POST)
        if form.is_valid():
            non = form.cleaned_data.get('non')
            modpas = form.cleaned_data.get('modpas')
            modpas2 = form.cleaned_data.get('modpas2')

            if User.objects.filter(username=non).exists():
                error_message = 'Ce nom d\'utilisateur est déjà utilisé.'
                context = {
                    'form': form,
                    'error_message': error_message
                }
                return render(request, 'newuser.html', context)

            user = User.objects.create_user(username=non, password=modpas)
            user.save()
            return redirect(akey)
        else:
            print('Le formulaire contient des erreurs')
    else:
        form = NewUserForm()
    context = {
        'form': form
    }
    return render(request, 'newuser.html', context)


def index(request):
    konekte = request.user.is_authenticated
    contacts = Contact.objects.all()
    search_input = request.GET.get('search-area')
    if search_input:
        contacts = Contact.objects.filter(full_name__icontains=search_input)
    else:
        contacts = Contact.objects.all()
        search_input = ''
    return render(request, 'index.html', {'contacts': contacts, 'search_input': search_input, 'konekte': konekte})

@login_required
def addContact(request):
        if request.method == 'POST':
            user = request.user
            full_name = request.POST['fullname']
            email = request.POST['email']
            phone_number = request.POST['phone-number']
            
            if Contact.objects.filter(Q(full_name=full_name) | Q(email=email) | Q(phone_number=phone_number)).exists():
                error_message = 'Ce contact existe déjà.'
                context = {
                    'error_message': error_message
                }
                return render(request, 'new.html', context)

            new_contact = Contact(
                user=user,
                full_name=full_name,
                relationship=request.POST['relationship'],
                email=email,
                phone_number=phone_number,
                address=request.POST['address'],
            )
            new_contact.save()
            return redirect('/')

        return render(request, 'new.html')
 
    

@login_required
def editContact(request, pk):
    contact = Contact.objects.get(id=pk)
    if request.user.is_authenticated:
        if request.method == 'POST':
            contact.full_name = request.POST['fullname']
            contact.relationship = request.POST['relationship']
            contact.email = request.POST['email']
            contact.phone_number = request.POST['phone-number']
            contact.address = request.POST['address']
            contact.save()
            return redirect('/profile/' + str(contact.id))
        return render(request, 'edit.html', {'contact': contact})
    else:
        return redirect('konekte')
    
    
@login_required
def deleteContact(request, pk):
    contact = Contact.objects.get(id=pk)
    if request.user.is_authenticated:
        if request.method == 'POST':
            contact.delete()
            return redirect('/')
        return render(request, 'delete.html', {'contact': contact})
    else:
        return redirect('konekte')

def contactProfile(request, pk):
    contact = Contact.objects.get(id=pk)
    return render(request, 'contact-profile.html', {'contact': contact})

templates/akey.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
<style>
  .navbar {
	background-color: #333; 
	color: #fff; 
	padding: 20px; 
	text-transform: uppercase; 
	font-size: 16px; 
	justify-content: flex-start;
  }
  
  .navbar ul {
	list-style: none;
	display: flex;
	flex-direction: row;
	margin: auto;
  }
  
  .navbar li {
	margin-right: 1rem;
	border: 1px solid #fff;
	padding: 5px 10px;
	border-radius: 5px;
  }
  
  .navbar a {
	color: #fff;
	text-decoration: none;
	font-weight: bold;
  }
  
  .navbar .title h1 {
	align-items: center;
	justify-content: center;
	color: #fff;
	display: flex;
  size: 10px;
  }
  
</style>

</head>
<body>


{% if user.is_authenticated %}
<nav class="navbar"> 
  <div class="title"><h1>CONTACT-BOOK </h1></div>

  <ul>
    <li><a href="{% url 'add-contact' %}">nouvo kontak</a></li>
    <li><a href="{% url 'index' %}">liste </a></li>
    <li><a href="{% url 'dekonekte' %}">dekonekte</a></li>
    
  </ul>
</nav>
<hr>



{% else %}
 <nav class="navbar">
  <div class="title"><h1>CONTACT-BOOK </h1></div>

  <ul>
    <li><a href="{% url 'index' %}">liste kontak yo</a></li>
    <li> <a href="{% url 'newuser' %}">inskri</a></li>
    <li> <a href="{% url 'konekte' %}">konekte</a></li>
  </ul>
</nav>


{% endif %}


  

templates/base.html
<!DOCTYPE html>
<html lang="en">
    
{% block head %}
<head>
<style>

.my-form-class {
    max-width: 300px; 
    margin: 0 auto;
    padding: 20px; 
    background-color: #f4f4f4; 
    border: 1px solid #ccc; 
    border-radius: 5px; 
}

.my-label-class {
    font-weight: bold; 
    display: block; 
}

.my-input-class {
    width: 100%; 
    padding: 10px; 
    margin: 5px 0; 
    border: 1px solid #ccc; 
    border-radius: 5px; 
    outline: none; 
}

.my-button-class {
    background-color: #333;
    color: #fff;
    padding: 10px 20px; 
    border: none; 
    border-radius: 5px; 
    cursor: pointer; 
    font-weight: bold; 
}

.title {
    justify-content: center;
    align-items: center;
    
}


</style>
    {% include 'akey.html' %}
{% endblock %}
</head>
<body>
    {% block body %}


    {% endblock %}
</body>
{% block footer %}
<footer>

 
</footer>
{% endblock %}
</html>

templates/contact-profile.html
{%  extends 'base.html' %}


{% load static %}


{% block body %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'style-profile.css' %}">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title> Profil</title>
</head>

<body>

	<div class="container">
		<header class="hero">
			<a href="/">
				<i class="fas fa-chevron-circle-left back-btn"></i>
			</a>
			<div class="hero-info">
				<h1 class="name">{{ contact.full_name | title }}</h1>
				<p class="relationship">{{ contact.relationship | title }}</p>
			</div>
		</header>

		<section class="contact-info">

			<div class="info-line">
				<i class="fas fa-phone icon-gradient"></i>
				<p class="phone-number">{{ contact.phone_number }}</p>
			</div>


			<div class="info-line">
				<i class="fas fa-sms icon-gradient"></i>
				<p class="sms">{{ contact.email }}</p>
			</div>



			<div id="address-info" class="info-line">
				<i id="location" class="fas fa-map-marker-alt icon-gradient"></i>
				<p class="address">{{ contact.address }}</p>
			</div>


		</section>


		<a href="{% url 'edit-contact' contact.id %}">
			<section class="edit-contact">
				<div class="edit-button">
					<i class="fas fa-cog icon-gradient"></i>
				</div>
			</section>
		</a>

	</div>

</body>

</html>
{% endblock %}

templates/delete.html
{%  extends 'base.html' %}

{% load static %}

{% block body %}


<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'style-delete.css' %}">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Efase</title>
</head>

<body>
	<div class="container">
		<header class="hero">
			<a href="{% url 'edit-contact' contact.id %}">
				<i class="fas fa-chevron-circle-left back-btn"></i>
			</a>
			<div class="hero-info">
				<h1 class="name">{{ contact.full_name | title }}</h1>
				<p class="relationship-hero">{{ contact.relationship | title }}</p>
			</div>
		</header>

		<section class="delete-container">
			<p>Eske'w sur ou vle Efase kontak saaa?</p>

			<form method='POST'>
				{% csrf_token %}
				<div class="delete-contact">
					<i class="fas fa-trash delete-icon"></i>
					<input class="delete-button" type="submit" value='Delete Contact' />
				</div>
			</form>

		</section>
	</div>

</body>

</html>
{% endblock %}

templates/edit.html
{%  extends 'base.html' %}

{% load static %}

{% block body %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'style-edit.css' %}">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Modifye</title>
</head>

<body>

	<div class='container'>
		<header class="hero">
			<a href="{% url 'profile' contact.id %}">
				<i class="fas fa-chevron-circle-left back-btn"></i>
			</a>
			<div class="hero-info">
				<h1 class="name">{{ contact.full_name | title }}</h1>
				<p class="relationship-hero">{{ contact.relationship | title }}</p>
			</div>
		</header>

		<form action="" method="POST">
			{% csrf_token %}
			<section class="contact-info">

				<div class="info-line">
					<i class="fas fa-phone icon-gradient"></i>
					<input type="text" class="type" name="fullname" placeholder="Full Name"
						value="{{ contact.full_name | title }}">
				</div>

				<div class="info-line">
					<i class="fas fa-user-circle icon-gradient"></i>
					<input type="text" class="type" name="relationship" placeholder="Relationship"
						value="{{ contact.relationship | title }}">
				</div>



				<div class="info-line">
					<i class="fas fa-sms icon-gradient"></i>
					<input type="text" class="type" name="phone-number" placeholder="Phone Number"
						value="{{ contact.phone_number }}">
				</div>



				<div class="info-line">
					<i class="fas fa-envelope icon-gradient"></i>
					<input type="text" class="type" name="email" placeholder="Email" value="{{ contact.email }}">
				</div>



				<div class="info-line">
					<i class="fas fa-map-marker-alt icon-gradient location"></i>
					<input type="text" class="type" name="address" placeholder="Address" value="{{ contact.address }}">
				</div>


			</section>

			<section class="button-container">
				<div class="update-contact">
					<i class="fas fa-check-circle icon-gradient"></i>
					<button class="button">Anregistre</button>
				</div>
			</section>
		</form>

		<section class="button-container">

			<a href="{% url 'delete' contact.id %}">
				<div class="update-contact">
					<i class="fas fa-trash icon-gradient"></i>
					<button class="button">Efase </button>
				</div>
			</a>

		</section>
	</div>

</body>


</html>
{% endblock %}

templates/index.html
{%  extends 'base.html' %}

{% load static %}

{% block body %}


<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>

	<title>list kontak yo</title>
</head>

<body>
	<div class="container">

		<header class="header">
			<form action="/" method="GET" class="search-bar" id='search-form'>

				<input type="search-name" class="contact-search" name="search-area" placeholder="Search"
					value={{search_input}}>

				<i onclick="document.getElementById('search-form').submit();" style="padding-left: 5px;"
					class="fas fa-search"></i>

			</form>
			{% if konekte %}

			<a href="{% url 'add-contact'  %}"><i class="fas fa-plus-circle add"></i></a>

			{%endif %}
		</header>

		<section class="contacts-library">
			<ul class="contacts-list">
				{% for contact in contacts reversed %}

				<a href="{% url 'profile' contact.id %}" style="text-decoration: none;">

					<div class="contact-section">
						<li class="list__item">


							<p class="contact-name">{{ contact.full_name | title }}</p>

							<p class="relationship">{{ contact.phone_number  }}</p>
						</li>

						<li id="call" class="list__item">
							<i class="fas fa-phone"></i>
							<i class="fas fa-sms text"></i>
						</li>
					</div>
				</a>

				<hr>


				{% empty %}
				<h3 style="color:#fff;padding:20px;">Nou pa jwenn kontak..</h3>
				{% endfor %}
			</ul>
		</section>
	</div>
</body>

</html>
{% endblock %}

templates/konekte.html
{% extends 'base.html' %}

{% block body %}

<form action='{% url "konekte" %}' method="post" class="my-form-class">
    <div class="title"><h3>KONEKTE</h3></div>

    {% csrf_token %}
    <label for="id_non" class="my-label-class">Non</label>
    <input type="text" id="id_non" name="non" required="required" class="my-input-class"><br><br>
    <label for="modpass" class="my-label-class">Modpas</label>
    <input type="password" id="id_modpass" name="modpas" required="required" class="my-input-class"><br><br>
    <button type="submit" class="my-button-class">Konekte</button>
</form>

{% endblock %}

templates/new.html
{%  extends 'base.html' %}

{% load static %}
{% block body %}


<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'style-edit.css' %}">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/6b20b1c14d.js" crossorigin="anonymous"></script>
	<title>Edit Contact</title>
</head>

<body>
	<div class='container'>
		<header class="hero">

			<a href="/">
				<i class="fas fa-chevron-circle-left back-btn"></i>
			</a>

			<div class="hero-info">
				<h1 class="name">Nouvo kontak</h1>
			</div>
		</header>

		<form action="" method="POST">
			{% csrf_token %}
			<section class="contact-info">

				<div class="info-line">
					<i class="fas fa-phone icon-gradient"></i>
					<input type="text" class="type" name="fullname" placeholder="Full Name">
				</div>

				<div class="info-line">
					<i class="fas fa-user-circle icon-gradient"></i>
					<input type="text" class="type" name="relationship" placeholder="Relationship">
				</div>



				<div class="info-line">
					<i class="fas fa-sms icon-gradient"></i>
					<input type="text" class="type" name="phone-number" placeholder="Phone Number">
				</div>




				<div class="info-line">
					<i class="fas fa-map-marker-alt icon-gradient location"></i>
					<input type="text" class="type" name="address" placeholder="Address">
				</div>


				<div class="info-line">
					<i class="fas fa-envelope icon-gradient location"></i>
					<input type="text" class="type" name="email" placeholder="Email">
				</div>



			</section>

			<section class="button-container">


				<div class="update-contact">
					<i id="save" class="fas fa-check-circle icon-gradient"></i>
					<button type=" submit" class="button"></button>
				</div>
			</section>


		</form>
	</div>

</body>

</html>
{% endblock %}

templates/newuser.html
{% extends 'base.html' %}

{% block body %}

<form action='{% url "newuser" %}' method="post" class="my-form-class">
    <div class="title"><h3>ENSKRI</h3></div>

    {% csrf_token %}
    <label for="id_non" class="my-label-class">Non</label>
    <input type="text" id="id_non" name="non" required="required" class="my-input-class"><br><br>
    <label for="modpass" class="my-label-class">Modpas</label>
    <input type="password" id="id_modpass" name "modpas" required="required" class="my-input-class"><br><br>
    <button type="submit" class="my-button-class">Antrejistre</button>
</form>

{% endblock %}